-- MySQL Script generated by MySQL Workbench
-- Thu Mar  5 21:35:59 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_nome` VARCHAR(45) NOT NULL,
  `usuario_cpf` VARCHAR(14) NOT NULL,
  `usuario_email` VARCHAR(150) NOT NULL,
  `usuario_sexo` ENUM('F', 'M', 'Outro') NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `usuario_cpf_UNIQUE` ON `mydb`.`usuario` (`usuario_cpf` ASC) VISIBLE;

CREATE UNIQUE INDEX `usuario_email_UNIQUE` ON `mydb`.`usuario` (`usuario_email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`telefone` ;

CREATE TABLE IF NOT EXISTS `mydb`.`telefone` (
  `telefone_id` INT NOT NULL AUTO_INCREMENT,
  `telefone_ddi` VARCHAR(4) NOT NULL,
  `telefone_ddd` VARCHAR(3) NOT NULL,
  `telefone_telefone` VARCHAR(9) NOT NULL,
  `telefone_principal` TINYINT NOT NULL DEFAULT 0,
  `usuario_usuario_id` INT NOT NULL,
  PRIMARY KEY (`telefone_id`),
  CONSTRAINT `fk_telefone_usuario1`
    FOREIGN KEY (`usuario_usuario_id`)
    REFERENCES `mydb`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_telefone_usuario1_idx` ON `mydb`.`telefone` (`usuario_usuario_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `estado_id` INT NOT NULL AUTO_INCREMENT,
  `estado_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`estado_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `estado_nome_UNIQUE` ON `mydb`.`estado` (`estado_nome` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cidade` (
  `cidade_id` INT NOT NULL AUTO_INCREMENT,
  `cidade_nome` VARCHAR(45) NOT NULL,
  `estado_estado_id` INT NOT NULL,
  PRIMARY KEY (`cidade_id`),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_estado_id`)
    REFERENCES `mydb`.`estado` (`estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cidade_estado1_idx` ON `mydb`.`cidade` (`estado_estado_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `index3` ON `mydb`.`cidade` (`cidade_nome` ASC, `estado_estado_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`CEP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CEP` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CEP` (
  `cep_id` INT NOT NULL AUTO_INCREMENT,
  `cep_numeracao` VARCHAR(11) NOT NULL,
  `cidade_cidade_id` INT NOT NULL,
  PRIMARY KEY (`cep_id`),
  CONSTRAINT `fk_CEP_cidade1`
    FOREIGN KEY (`cidade_cidade_id`)
    REFERENCES `mydb`.`cidade` (`cidade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CEP_cidade1_idx` ON `mydb`.`CEP` (`cidade_cidade_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `cep_numeracao_UNIQUE` ON `mydb`.`CEP` (`cep_numeracao` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `endereco_id` INT NOT NULL AUTO_INCREMENT,
  `endereco_identificacao` VARCHAR(45) NOT NULL,
  `endereco_logradouro` VARCHAR(45) NOT NULL,
  `endereco_numero` INT NULL,
  `usuario_usuario_id` INT NOT NULL,
  `CEP_cep_id` INT NOT NULL,
  PRIMARY KEY (`endereco_id`),
  CONSTRAINT `fk_endereco_usuario1`
    FOREIGN KEY (`usuario_usuario_id`)
    REFERENCES `mydb`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_CEP1`
    FOREIGN KEY (`CEP_cep_id`)
    REFERENCES `mydb`.`CEP` (`cep_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_endereco_usuario1_idx` ON `mydb`.`endereco` (`usuario_usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_endereco_CEP1_idx` ON `mydb`.`endereco` (`CEP_cep_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`tipoEvento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipoEvento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipoEvento` (
  `tipoEvento_id` INT NOT NULL AUTO_INCREMENT,
  `tipoEvento_nome` VARCHAR(45) NOT NULL,
  `tipoEvento_descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`tipoEvento_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`local`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`local` ;

CREATE TABLE IF NOT EXISTS `mydb`.`local` (
  `local_id` INT NOT NULL AUTO_INCREMENT,
  `local_nome` VARCHAR(45) NOT NULL,
  `local_descricao` VARCHAR(100) NULL,
  `local_capacidade` INT NULL,
  `local_endereco` VARCHAR(45) NULL,
  `CEP_cep_id` INT NOT NULL,
  PRIMARY KEY (`local_id`),
  CONSTRAINT `fk_local_CEP1`
    FOREIGN KEY (`CEP_cep_id`)
    REFERENCES `mydb`.`CEP` (`cep_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_local_CEP1_idx` ON `mydb`.`local` (`CEP_cep_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`eventos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`eventos` (
  `eventos_id` INT NOT NULL AUTO_INCREMENT,
  `eventos_nome` VARCHAR(45) NOT NULL,
  `eventos_descricao` VARCHAR(100) NOT NULL,
  `eventos_dataInicio` DATE NOT NULL,
  `eventos_dataFim` DATE NOT NULL,
  `eventos_dataLimiteInscricao` DATETIME NOT NULL,
  `tipoEvento_tipoEvento_id` INT NOT NULL,
  `local_local_id` INT NOT NULL,
  PRIMARY KEY (`eventos_id`),
  CONSTRAINT `fk_eventos_tipoEvento1`
    FOREIGN KEY (`tipoEvento_tipoEvento_id`)
    REFERENCES `mydb`.`tipoEvento` (`tipoEvento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_local1`
    FOREIGN KEY (`local_local_id`)
    REFERENCES `mydb`.`local` (`local_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_eventos_tipoEvento1_idx` ON `mydb`.`eventos` (`tipoEvento_tipoEvento_id` ASC) VISIBLE;

CREATE INDEX `fk_eventos_local1_idx` ON `mydb`.`eventos` (`local_local_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`tipoInscricao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipoInscricao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipoInscricao` (
  `tipoInscricao_id` INT NOT NULL AUTO_INCREMENT,
  `tipoInscricao_nome` VARCHAR(45) NOT NULL,
  `tipoInscricao_descricao` VARCHAR(100) NULL,
  `tipoInscricao_valor` DECIMAL(10,2) NOT NULL,
  `eventos_eventos_id` INT NOT NULL,
  PRIMARY KEY (`tipoInscricao_id`),
  CONSTRAINT `fk_tipoInscricao_eventos1`
    FOREIGN KEY (`eventos_eventos_id`)
    REFERENCES `mydb`.`eventos` (`eventos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tipoInscricao_eventos1_idx` ON `mydb`.`tipoInscricao` (`eventos_eventos_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`inscricao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inscricao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inscricao` (
  `inscricao_id` INT NOT NULL AUTO_INCREMENT,
  `inscricao_credenciamento` TINYINT NOT NULL DEFAULT 0,
  `eventos_eventos_id` INT NOT NULL,
  `usuario_usuario_id` INT NOT NULL,
  `tipoInscricao_tipoInscricao_id` INT NOT NULL,
  PRIMARY KEY (`inscricao_id`),
  CONSTRAINT `fk_inscritos_eventos1`
    FOREIGN KEY (`eventos_eventos_id`)
    REFERENCES `mydb`.`eventos` (`eventos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscritos_usuario1`
    FOREIGN KEY (`usuario_usuario_id`)
    REFERENCES `mydb`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscritos_tipoInscricao1`
    FOREIGN KEY (`tipoInscricao_tipoInscricao_id`)
    REFERENCES `mydb`.`tipoInscricao` (`tipoInscricao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_inscritos_eventos1_idx` ON `mydb`.`inscricao` (`eventos_eventos_id` ASC) VISIBLE;

CREATE INDEX `fk_inscritos_usuario1_idx` ON `mydb`.`inscricao` (`usuario_usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_inscritos_tipoInscricao1_idx` ON `mydb`.`inscricao` (`tipoInscricao_tipoInscricao_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`programacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`programacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`programacao` (
  `programacao_id` INT NOT NULL AUTO_INCREMENT,
  `programacao_horaInicio` DATETIME NOT NULL,
  `programacao_horaFim` DATETIME NOT NULL,
  `programacao_nome` VARCHAR(45) NOT NULL,
  `programacao_linkPresenca` VARCHAR(45) NOT NULL,
  `programacao_descricao` VARCHAR(100) NULL,
  `eventos_eventos_id` INT NOT NULL,
  `local_local_id` INT NOT NULL,
  PRIMARY KEY (`programacao_id`),
  CONSTRAINT `fk_programacao_eventos1`
    FOREIGN KEY (`eventos_eventos_id`)
    REFERENCES `mydb`.`eventos` (`eventos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_programacao_local1`
    FOREIGN KEY (`local_local_id`)
    REFERENCES `mydb`.`local` (`local_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_programacao_eventos1_idx` ON `mydb`.`programacao` (`eventos_eventos_id` ASC) VISIBLE;

CREATE INDEX `fk_programacao_local1_idx` ON `mydb`.`programacao` (`local_local_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`certificados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`certificados` ;

CREATE TABLE IF NOT EXISTS `mydb`.`certificados` (
  `certificados_id` INT NOT NULL AUTO_INCREMENT,
  `certificados_codigoDeValidacao` VARCHAR(100) NOT NULL,
  `certificados_cargaHorariaTotal` DECIMAL(5,2) NOT NULL,
  `certificados_status` VARCHAR(20) NOT NULL DEFAULT 'valido',
  `certificados_dataRevogacao` DATETIME NULL,
  `certificados_motivoRevogacao` LONGTEXT NULL,
  `certificados_dataDeEmissao` DATETIME NOT NULL,
  `certificados_urlArquivo` VARCHAR(255) NOT NULL,
  `inscricao_inscricao_id` INT NOT NULL,
  PRIMARY KEY (`certificados_id`),
  CONSTRAINT `fk_certificados_inscricao1`
    FOREIGN KEY (`inscricao_inscricao_id`)
    REFERENCES `mydb`.`inscricao` (`inscricao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `certificados_codigoDeValidacao_UNIQUE` ON `mydb`.`certificados` (`certificados_codigoDeValidacao` ASC) VISIBLE;

CREATE INDEX `fk_certificados_inscricao1_idx` ON `mydb`.`certificados` (`inscricao_inscricao_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`tiposLogin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tiposLogin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tiposLogin` (
  `tiposLogin_id` INT NOT NULL AUTO_INCREMENT,
  `tiposLogin_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tiposLogin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`login` ;

CREATE TABLE IF NOT EXISTS `mydb`.`login` (
  `login_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_usuario_id` INT NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `tiposLogin_tiposLogin_id` INT NOT NULL,
  PRIMARY KEY (`login_id`),
  CONSTRAINT `fk_login_usuario1`
    FOREIGN KEY (`usuario_usuario_id`)
    REFERENCES `mydb`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_login_tiposLogin1`
    FOREIGN KEY (`tiposLogin_tiposLogin_id`)
    REFERENCES `mydb`.`tiposLogin` (`tiposLogin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_login_usuario1_idx` ON `mydb`.`login` (`usuario_usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_login_tiposLogin1_idx` ON `mydb`.`login` (`tiposLogin_tiposLogin_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `index4` ON `mydb`.`login` (`usuario_usuario_id` ASC, `tiposLogin_tiposLogin_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`permissoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`permissoes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`permissoes` (
  `permissoes_id` INT NOT NULL AUTO_INCREMENT,
  `permissoes_nome` VARCHAR(45) NOT NULL,
  `permissoes_descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`permissoes_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`papel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`papel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`papel` (
  `papel_id` INT NOT NULL AUTO_INCREMENT,
  `papel_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`papel_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`voucher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`voucher` ;

CREATE TABLE IF NOT EXISTS `mydb`.`voucher` (
  `voucher_id` INT NOT NULL AUTO_INCREMENT,
  `voucher_codigo` VARCHAR(50) NOT NULL,
  `voucher_valor` DECIMAL(10,2) NOT NULL,
  `voucher_dataValidade` DATETIME NULL,
  `voucher_usoMaximo` INT UNSIGNED NOT NULL DEFAULT 1,
  `eventos_eventos_id` INT NOT NULL,
  `tipoInscricao_tipoInscricao_id` INT NOT NULL,
  PRIMARY KEY (`voucher_id`),
  CONSTRAINT `fk_voucher_eventos1`
    FOREIGN KEY (`eventos_eventos_id`)
    REFERENCES `mydb`.`eventos` (`eventos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voucher_tipoInscricao1`
    FOREIGN KEY (`tipoInscricao_tipoInscricao_id`)
    REFERENCES `mydb`.`tipoInscricao` (`tipoInscricao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `voucher_codigo_UNIQUE` ON `mydb`.`voucher` (`voucher_codigo` ASC) VISIBLE;

CREATE INDEX `fk_voucher_eventos1_idx` ON `mydb`.`voucher` (`eventos_eventos_id` ASC) VISIBLE;

CREATE INDEX `fk_voucher_tipoInscricao1_idx` ON `mydb`.`voucher` (`tipoInscricao_tipoInscricao_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`metodoPagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`metodoPagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`metodoPagamento` (
  `metodoPagamento_id` INT NOT NULL AUTO_INCREMENT,
  `formaDePagamento` VARCHAR(45) NULL,
  PRIMARY KEY (`metodoPagamento_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipoDesconto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipoDesconto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipoDesconto` (
  `tipoDesconto_id` INT NOT NULL AUTO_INCREMENT,
  `tipoDesconto_nome` VARCHAR(45) NOT NULL,
  `tipoDesconto_descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`tipoDesconto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `pagamento_id` INT NOT NULL AUTO_INCREMENT,
  `pagamento_valorPagamento` DECIMAL(9,2) NOT NULL,
  `pagamento_status` ENUM('Pendente', 'Pago', 'Agendado') NOT NULL DEFAULT 'Pendente',
  `pagamento_valorTotal` DECIMAL(9,2) NOT NULL,
  `pagamento_dataHora` DATETIME NOT NULL,
  `metodoPagamento_metodoPagamento_id` INT NOT NULL,
  `voucher_voucher_id` INT NULL,
  `inscricao_inscricao_id` INT NOT NULL,
  `tipoDesconto_tipoDesconto_id` INT NULL,
  PRIMARY KEY (`pagamento_id`),
  CONSTRAINT `fk_pagamento_metodoPagamento1`
    FOREIGN KEY (`metodoPagamento_metodoPagamento_id`)
    REFERENCES `mydb`.`metodoPagamento` (`metodoPagamento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_voucher1`
    FOREIGN KEY (`voucher_voucher_id`)
    REFERENCES `mydb`.`voucher` (`voucher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_inscricao1`
    FOREIGN KEY (`inscricao_inscricao_id`)
    REFERENCES `mydb`.`inscricao` (`inscricao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_tipoDesconto1`
    FOREIGN KEY (`tipoDesconto_tipoDesconto_id`)
    REFERENCES `mydb`.`tipoDesconto` (`tipoDesconto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pagamento_metodoPagamento1_idx` ON `mydb`.`pagamento` (`metodoPagamento_metodoPagamento_id` ASC) VISIBLE;

CREATE INDEX `fk_pagamento_voucher1_idx` ON `mydb`.`pagamento` (`voucher_voucher_id` ASC) VISIBLE;

CREATE INDEX `fk_pagamento_inscricao1_idx` ON `mydb`.`pagamento` (`inscricao_inscricao_id` ASC) VISIBLE;

CREATE INDEX `fk_pagamento_tipoDesconto1_idx` ON `mydb`.`pagamento` (`tipoDesconto_tipoDesconto_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`permissoesUsuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`permissoesUsuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`permissoesUsuarios` (
  `permissoes_permissoes_id` INT NOT NULL,
  `usuario_usuario_id` INT NOT NULL,
  PRIMARY KEY (`permissoes_permissoes_id`, `usuario_usuario_id`),
  CONSTRAINT `fk_permissoes_has_usuario_permissoes1`
    FOREIGN KEY (`permissoes_permissoes_id`)
    REFERENCES `mydb`.`permissoes` (`permissoes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permissoes_has_usuario_usuario1`
    FOREIGN KEY (`usuario_usuario_id`)
    REFERENCES `mydb`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_permissoes_has_usuario_usuario1_idx` ON `mydb`.`permissoesUsuarios` (`usuario_usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_permissoes_has_usuario_permissoes1_idx` ON `mydb`.`permissoesUsuarios` (`permissoes_permissoes_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`inscritosProgramacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inscritosProgramacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inscritosProgramacao` (
  `inscritosProgramacao_id` INT NOT NULL AUTO_INCREMENT,
  `inscritos_inscritos_id` INT NOT NULL,
  `programacao_programacao_id` INT NOT NULL,
  `inscritosProgramacao_dataHoraFrequencia` DATETIME NULL,
  `inscritosProgramacao_FrequenciaConfirmada` TINYINT NULL,
  PRIMARY KEY (`inscritosProgramacao_id`),
  CONSTRAINT `fk_inscritos_has_programacao_inscritos1`
    FOREIGN KEY (`inscritos_inscritos_id`)
    REFERENCES `mydb`.`inscricao` (`inscricao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscritos_has_programacao_programacao1`
    FOREIGN KEY (`programacao_programacao_id`)
    REFERENCES `mydb`.`programacao` (`programacao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_inscritos_has_programacao_programacao1_idx` ON `mydb`.`inscritosProgramacao` (`programacao_programacao_id` ASC) VISIBLE;

CREATE INDEX `fk_inscritos_has_programacao_inscritos1_idx` ON `mydb`.`inscritosProgramacao` (`inscritos_inscritos_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`imagemEvento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`imagemEvento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`imagemEvento` (
  `imagemEvento_ID` INT NOT NULL AUTO_INCREMENT,
  `imagemEvento_caminho` VARCHAR(45) NOT NULL,
  `imagemEvento_descricao` VARCHAR(45) NULL,
  `eventos_eventos_id` INT NOT NULL,
  PRIMARY KEY (`imagemEvento_ID`),
  CONSTRAINT `fk_imagemEvento_eventos1`
    FOREIGN KEY (`eventos_eventos_id`)
    REFERENCES `mydb`.`eventos` (`eventos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_imagemEvento_eventos1_idx` ON `mydb`.`imagemEvento` (`eventos_eventos_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`papelProgramacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`papelProgramacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`papelProgramacao` (
  `papelProgramacao_id` INT NOT NULL AUTO_INCREMENT,
  `inscricao_inscricao_id` INT NOT NULL,
  `papel_papel_id` INT NOT NULL,
  `programacao_programacao_id` INT NOT NULL,
  PRIMARY KEY (`papelProgramacao_id`),
  CONSTRAINT `fk_inscricao_has_papel_inscricao1`
    FOREIGN KEY (`inscricao_inscricao_id`)
    REFERENCES `mydb`.`inscricao` (`inscricao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscricao_has_papel_papel1`
    FOREIGN KEY (`papel_papel_id`)
    REFERENCES `mydb`.`papel` (`papel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_papelProgramacao_programacao1`
    FOREIGN KEY (`programacao_programacao_id`)
    REFERENCES `mydb`.`programacao` (`programacao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_inscricao_has_papel_papel1_idx` ON `mydb`.`papelProgramacao` (`papel_papel_id` ASC) VISIBLE;

CREATE INDEX `fk_inscricao_has_papel_inscricao1_idx` ON `mydb`.`papelProgramacao` (`inscricao_inscricao_id` ASC) VISIBLE;

CREATE INDEX `fk_papelProgramacao_programacao1_idx` ON `mydb`.`papelProgramacao` (`programacao_programacao_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `index5` ON `mydb`.`papelProgramacao` (`papel_papel_id` ASC, `inscricao_inscricao_id` ASC, `programacao_programacao_id` ASC) INVISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`imagemProgramacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`imagemProgramacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`imagemProgramacao` (
  `imagemProgramacao_ID` INT NOT NULL AUTO_INCREMENT,
  `imagemProgramacao_caminho` VARCHAR(45) NOT NULL,
  `imagemProgramacao_descricao` VARCHAR(45) NULL,
  `programacao_programacao_id` INT NOT NULL,
  PRIMARY KEY (`imagemProgramacao_ID`),
  CONSTRAINT `fk_imagemProgramacao_programacao1`
    FOREIGN KEY (`programacao_programacao_id`)
    REFERENCES `mydb`.`programacao` (`programacao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_imagemProgramacao_programacao1_idx` ON `mydb`.`imagemProgramacao` (`programacao_programacao_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
