-- MySQL Script generated by MySQL Workbench
-- Sun Apr 26 03:22:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eventos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `eventos` ;

-- -----------------------------------------------------
-- Schema eventos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eventos` DEFAULT CHARACTER SET utf8 ;
USE `eventos` ;

-- -----------------------------------------------------
-- Table `eventos`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`usuario` ;

CREATE TABLE IF NOT EXISTS `eventos`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_nome` VARCHAR(45) NOT NULL,
  `usuario_cpf` VARCHAR(14) NOT NULL,
  `usuario_email` VARCHAR(150) NOT NULL,
  `usuario_sexo` ENUM('F', 'M', 'Outro') NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `usuario_cpf_UNIQUE` ON `eventos`.`usuario` (`usuario_cpf` ASC) VISIBLE;

CREATE UNIQUE INDEX `usuario_email_UNIQUE` ON `eventos`.`usuario` (`usuario_email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`telefone` ;

CREATE TABLE IF NOT EXISTS `eventos`.`telefone` (
  `telefone_id` INT NOT NULL AUTO_INCREMENT,
  `telefone_ddi` VARCHAR(4) NOT NULL,
  `telefone_ddd` VARCHAR(3) NOT NULL,
  `telefone_telefone` VARCHAR(9) NOT NULL,
  `telefone_principal` TINYINT NOT NULL DEFAULT 0,
  `telefone_usuario_id` INT NOT NULL,
  PRIMARY KEY (`telefone_id`),
  CONSTRAINT `fk_telefone_usuario1`
    FOREIGN KEY (`telefone_usuario_id`)
    REFERENCES `eventos`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_telefone_usuario1_idx` ON `eventos`.`telefone` (`telefone_usuario_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`estado` ;

CREATE TABLE IF NOT EXISTS `eventos`.`estado` (
  `estado_id` INT NOT NULL AUTO_INCREMENT,
  `estado_nome` VARCHAR(45) NOT NULL,
  `estado_sigla` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`estado_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `estado_nome_UNIQUE` ON `eventos`.`estado` (`estado_nome` ASC) VISIBLE;

CREATE UNIQUE INDEX `estado_sigla_UNIQUE` ON `eventos`.`estado` (`estado_sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`cidade` ;

CREATE TABLE IF NOT EXISTS `eventos`.`cidade` (
  `cidade_id` INT NOT NULL AUTO_INCREMENT,
  `cidade_nome` VARCHAR(45) NOT NULL,
  `cidade_estado_id` INT NOT NULL,
  PRIMARY KEY (`cidade_id`),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`cidade_estado_id`)
    REFERENCES `eventos`.`estado` (`estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cidade_estado1_idx` ON `eventos`.`cidade` (`cidade_estado_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `index3` ON `eventos`.`cidade` (`cidade_nome` ASC, `cidade_estado_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`CEP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`CEP` ;

CREATE TABLE IF NOT EXISTS `eventos`.`CEP` (
  `cep_id` INT NOT NULL AUTO_INCREMENT,
  `cep_numeracao` VARCHAR(11) NOT NULL,
  `cep_cidade_id` INT NOT NULL,
  PRIMARY KEY (`cep_id`),
  CONSTRAINT `fk_CEP_cidade1`
    FOREIGN KEY (`cep_cidade_id`)
    REFERENCES `eventos`.`cidade` (`cidade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CEP_cidade1_idx` ON `eventos`.`CEP` (`cep_cidade_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `cep_numeracao_UNIQUE` ON `eventos`.`CEP` (`cep_numeracao` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`endereco` ;

CREATE TABLE IF NOT EXISTS `eventos`.`endereco` (
  `endereco_id` INT NOT NULL AUTO_INCREMENT,
  `endereco_identificacao` VARCHAR(45) NOT NULL,
  `endereco_logradouro` VARCHAR(45) NOT NULL,
  `endereco_numero` INT NULL,
  `endereco_usuario_id` INT NOT NULL,
  `endereco_cep_id` INT NOT NULL,
  PRIMARY KEY (`endereco_id`),
  CONSTRAINT `fk_endereco_usuario1`
    FOREIGN KEY (`endereco_usuario_id`)
    REFERENCES `eventos`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_CEP1`
    FOREIGN KEY (`endereco_cep_id`)
    REFERENCES `eventos`.`CEP` (`cep_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_endereco_usuario1_idx` ON `eventos`.`endereco` (`endereco_usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_endereco_CEP1_idx` ON `eventos`.`endereco` (`endereco_cep_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`tipoEvento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`tipoEvento` ;

CREATE TABLE IF NOT EXISTS `eventos`.`tipoEvento` (
  `tipoEvento_id` INT NOT NULL AUTO_INCREMENT,
  `tipoEvento_nome` VARCHAR(45) NOT NULL,
  `tipoEvento_descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`tipoEvento_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos`.`localEvento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`localEvento` ;

CREATE TABLE IF NOT EXISTS `eventos`.`localEvento` (
  `localEvento_id` INT NOT NULL AUTO_INCREMENT,
  `localEvento_nome` VARCHAR(45) NOT NULL,
  `localEvento_descricao` VARCHAR(100) NULL,
  `localEvento_capacidade` INT NULL,
  `localEvento_endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`localEvento_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos`.`eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`eventos` ;

CREATE TABLE IF NOT EXISTS `eventos`.`eventos` (
  `eventos_id` INT NOT NULL AUTO_INCREMENT,
  `eventos_nome` VARCHAR(45) NOT NULL,
  `eventos_descricao` VARCHAR(100) NOT NULL,
  `eventos_dataInicio` DATE NOT NULL,
  `eventos_dataFim` DATE NOT NULL,
  `eventos_dataLimiteInscricao` DATETIME NOT NULL,
  `eventos_tipoEvento_id` INT NOT NULL,
  `eventos_local_id` INT NOT NULL,
  `eventos_criador_usuario_id` INT NOT NULL,
  PRIMARY KEY (`eventos_id`),
  CONSTRAINT `fk_eventos_tipoEvento1`
    FOREIGN KEY (`eventos_tipoEvento_id`)
    REFERENCES `eventos`.`tipoEvento` (`tipoEvento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_local1`
    FOREIGN KEY (`eventos_local_id`)
    REFERENCES `eventos`.`localEvento` (`localEvento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_usuario1`
    FOREIGN KEY (`eventos_criador_usuario_id`)
    REFERENCES `eventos`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_eventos_tipoEvento1_idx` ON `eventos`.`eventos` (`eventos_tipoEvento_id` ASC) VISIBLE;

CREATE INDEX `fk_eventos_local1_idx` ON `eventos`.`eventos` (`eventos_local_id` ASC) VISIBLE;

CREATE INDEX `fk_eventos_usuario1_idx` ON `eventos`.`eventos` (`eventos_criador_usuario_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`tipoInscricao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`tipoInscricao` ;

CREATE TABLE IF NOT EXISTS `eventos`.`tipoInscricao` (
  `tipoInscricao_id` INT NOT NULL AUTO_INCREMENT,
  `tipoInscricao_nome` VARCHAR(45) NOT NULL,
  `tipoInscricao_descricao` VARCHAR(100) NULL,
  `tipoInscricao_valor` DECIMAL(10,2) NOT NULL,
  `tipoInscricao_eventos_id` INT NOT NULL,
  PRIMARY KEY (`tipoInscricao_id`),
  CONSTRAINT `fk_tipoInscricao_eventos1`
    FOREIGN KEY (`tipoInscricao_eventos_id`)
    REFERENCES `eventos`.`eventos` (`eventos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tipoInscricao_eventos1_idx` ON `eventos`.`tipoInscricao` (`tipoInscricao_eventos_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`inscricao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`inscricao` ;

CREATE TABLE IF NOT EXISTS `eventos`.`inscricao` (
  `inscricao_id` INT NOT NULL AUTO_INCREMENT,
  `inscricao_credenciamento` TINYINT NOT NULL DEFAULT 0,
  `inscricao_eventos_id` INT NOT NULL,
  `inscricao_usuario_id` INT NOT NULL,
  `inscricao_tipoInscricao_id` INT NOT NULL,
  PRIMARY KEY (`inscricao_id`),
  CONSTRAINT `fk_inscritos_eventos1`
    FOREIGN KEY (`inscricao_eventos_id`)
    REFERENCES `eventos`.`eventos` (`eventos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscritos_usuario1`
    FOREIGN KEY (`inscricao_usuario_id`)
    REFERENCES `eventos`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscritos_tipoInscricao1`
    FOREIGN KEY (`inscricao_tipoInscricao_id`)
    REFERENCES `eventos`.`tipoInscricao` (`tipoInscricao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_inscritos_eventos1_idx` ON `eventos`.`inscricao` (`inscricao_eventos_id` ASC) VISIBLE;

CREATE INDEX `fk_inscritos_usuario1_idx` ON `eventos`.`inscricao` (`inscricao_usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_inscritos_tipoInscricao1_idx` ON `eventos`.`inscricao` (`inscricao_tipoInscricao_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`sublocalEvento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`sublocalEvento` ;

CREATE TABLE IF NOT EXISTS `eventos`.`sublocalEvento` (
  `sublocalEvento_id` INT NOT NULL AUTO_INCREMENT,
  `sublocalEvento_nome` VARCHAR(45) NOT NULL,
  `sublocalEvento_descricao` VARCHAR(200) NULL,
  `sublocalEvento_capacidade` INT NOT NULL,
  `sublocalEvento_localEvento_id` INT NOT NULL,
  PRIMARY KEY (`sublocalEvento_id`),
  CONSTRAINT `fk_sublocaEvento_localEvento1`
    FOREIGN KEY (`sublocalEvento_localEvento_id`)
    REFERENCES `eventos`.`localEvento` (`localEvento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sublocaEvento_localEvento1_idx` ON `eventos`.`sublocalEvento` (`sublocalEvento_localEvento_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`programacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`programacao` ;

CREATE TABLE IF NOT EXISTS `eventos`.`programacao` (
  `programacao_id` INT NOT NULL AUTO_INCREMENT,
  `programacao_horaInicio` DATETIME NOT NULL,
  `programacao_horaFim` DATETIME NOT NULL,
  `programacao_nome` VARCHAR(45) NOT NULL,
  `programacao_linkPresenca` VARCHAR(45) NOT NULL,
  `programacao_descricao` VARCHAR(100) NULL,
  `programacao_eventos_id` INT NOT NULL,
  `programacao_sublocaEvento_id` INT NOT NULL,
  PRIMARY KEY (`programacao_id`),
  CONSTRAINT `fk_programacao_eventos1`
    FOREIGN KEY (`programacao_eventos_id`)
    REFERENCES `eventos`.`eventos` (`eventos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_programacao_sublocaEvento1`
    FOREIGN KEY (`programacao_sublocaEvento_id`)
    REFERENCES `eventos`.`sublocalEvento` (`sublocalEvento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_programacao_eventos1_idx` ON `eventos`.`programacao` (`programacao_eventos_id` ASC) VISIBLE;

CREATE INDEX `fk_programacao_sublocaEvento1_idx` ON `eventos`.`programacao` (`programacao_sublocaEvento_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`certificados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`certificados` ;

CREATE TABLE IF NOT EXISTS `eventos`.`certificados` (
  `certificados_id` INT NOT NULL AUTO_INCREMENT,
  `certificados_codigoDeValidacao` VARCHAR(100) NOT NULL,
  `certificados_cargaHorariaTotal` DECIMAL(5,2) NOT NULL,
  `certificados_status` VARCHAR(20) NOT NULL DEFAULT 'valido',
  `certificados_dataRevogacao` DATETIME NULL,
  `certificados_motivoRevogacao` LONGTEXT NULL,
  `certificados_dataDeEmissao` DATETIME NOT NULL,
  `certificados_urlArquivo` VARCHAR(255) NOT NULL,
  `certificados_inscricao_id` INT NOT NULL,
  PRIMARY KEY (`certificados_id`),
  CONSTRAINT `fk_certificados_inscricao1`
    FOREIGN KEY (`certificados_inscricao_id`)
    REFERENCES `eventos`.`inscricao` (`inscricao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `certificados_codigoDeValidacao_UNIQUE` ON `eventos`.`certificados` (`certificados_codigoDeValidacao` ASC) VISIBLE;

CREATE INDEX `fk_certificados_inscricao1_idx` ON `eventos`.`certificados` (`certificados_inscricao_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`tiposLogin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`tiposLogin` ;

CREATE TABLE IF NOT EXISTS `eventos`.`tiposLogin` (
  `tiposLogin_id` INT NOT NULL AUTO_INCREMENT,
  `tiposLogin_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tiposLogin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`login` ;

CREATE TABLE IF NOT EXISTS `eventos`.`login` (
  `login_id` INT NOT NULL AUTO_INCREMENT,
  `login_usuario_id` INT NOT NULL,
  `login_tiposLogin_id` INT NOT NULL,
  `login_senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`login_id`, `login_usuario_id`, `login_tiposLogin_id`),
  CONSTRAINT `fk_login_usuario1`
    FOREIGN KEY (`login_usuario_id`)
    REFERENCES `eventos`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_login_tiposLogin1`
    FOREIGN KEY (`login_tiposLogin_id`)
    REFERENCES `eventos`.`tiposLogin` (`tiposLogin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_login_usuario1_idx` ON `eventos`.`login` (`login_usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_login_tiposLogin1_idx` ON `eventos`.`login` (`login_tiposLogin_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `index4` ON `eventos`.`login` (`login_usuario_id` ASC, `login_tiposLogin_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`permissoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`permissoes` ;

CREATE TABLE IF NOT EXISTS `eventos`.`permissoes` (
  `permissoes_id` INT NOT NULL AUTO_INCREMENT,
  `permissoes_nome` VARCHAR(45) NOT NULL,
  `permissoes_descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`permissoes_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos`.`papel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`papel` ;

CREATE TABLE IF NOT EXISTS `eventos`.`papel` (
  `papel_id` INT NOT NULL AUTO_INCREMENT,
  `papel_nome` VARCHAR(45) NOT NULL,
  `papel_descricao` VARCHAR(250) NULL,
  PRIMARY KEY (`papel_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos`.`voucher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`voucher` ;

CREATE TABLE IF NOT EXISTS `eventos`.`voucher` (
  `voucher_id` INT NOT NULL AUTO_INCREMENT,
  `voucher_codigo` VARCHAR(50) NOT NULL,
  `voucher_valor` DECIMAL(10,2) NOT NULL,
  `voucher_dataValidade` DATETIME NULL,
  `voucher_disponivel` TINYINT NOT NULL DEFAULT 1,
  `voucher_eventos_id` INT NOT NULL,
  `voucher_tipoInscricao_id` INT NOT NULL,
  PRIMARY KEY (`voucher_id`),
  CONSTRAINT `fk_voucher_eventos1`
    FOREIGN KEY (`voucher_eventos_id`)
    REFERENCES `eventos`.`eventos` (`eventos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voucher_tipoInscricao1`
    FOREIGN KEY (`voucher_tipoInscricao_id`)
    REFERENCES `eventos`.`tipoInscricao` (`tipoInscricao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `voucher_codigo_UNIQUE` ON `eventos`.`voucher` (`voucher_codigo` ASC) VISIBLE;

CREATE INDEX `fk_voucher_eventos1_idx` ON `eventos`.`voucher` (`voucher_eventos_id` ASC) VISIBLE;

CREATE INDEX `fk_voucher_tipoInscricao1_idx` ON `eventos`.`voucher` (`voucher_tipoInscricao_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`metodoPagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`metodoPagamento` ;

CREATE TABLE IF NOT EXISTS `eventos`.`metodoPagamento` (
  `metodoPagamento_id` INT NOT NULL AUTO_INCREMENT,
  `metodoPagamento_formaDePagamento` VARCHAR(45) NULL,
  PRIMARY KEY (`metodoPagamento_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos`.`tipoDesconto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`tipoDesconto` ;

CREATE TABLE IF NOT EXISTS `eventos`.`tipoDesconto` (
  `tipoDesconto_id` INT NOT NULL AUTO_INCREMENT,
  `tipoDesconto_nome` VARCHAR(45) NOT NULL,
  `tipoDesconto_descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`tipoDesconto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos`.`pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`pagamento` ;

CREATE TABLE IF NOT EXISTS `eventos`.`pagamento` (
  `pagamento_id` INT NOT NULL AUTO_INCREMENT,
  `pagamento_valorPagamento` DECIMAL(9,2) NOT NULL,
  `pagamento_status` ENUM('Pendente', 'Pago', 'Agendado') NOT NULL DEFAULT 'Pendente',
  `pagamento_valorTotal` DECIMAL(9,2) NOT NULL,
  `pagamento_dataHora` DATETIME NOT NULL,
  `pagamento_metodoPagamento_id` INT NOT NULL,
  `pagamento_voucher_id` INT NULL,
  `pagamento_inscricao_id` INT NOT NULL,
  `pagamento_tipoDesconto_id` INT NULL,
  PRIMARY KEY (`pagamento_id`),
  CONSTRAINT `fk_pagamento_metodoPagamento1`
    FOREIGN KEY (`pagamento_metodoPagamento_id`)
    REFERENCES `eventos`.`metodoPagamento` (`metodoPagamento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_voucher1`
    FOREIGN KEY (`pagamento_voucher_id`)
    REFERENCES `eventos`.`voucher` (`voucher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_inscricao1`
    FOREIGN KEY (`pagamento_inscricao_id`)
    REFERENCES `eventos`.`inscricao` (`inscricao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_tipoDesconto1`
    FOREIGN KEY (`pagamento_tipoDesconto_id`)
    REFERENCES `eventos`.`tipoDesconto` (`tipoDesconto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pagamento_metodoPagamento1_idx` ON `eventos`.`pagamento` (`pagamento_metodoPagamento_id` ASC) VISIBLE;

CREATE INDEX `fk_pagamento_voucher1_idx` ON `eventos`.`pagamento` (`pagamento_voucher_id` ASC) VISIBLE;

CREATE INDEX `fk_pagamento_inscricao1_idx` ON `eventos`.`pagamento` (`pagamento_inscricao_id` ASC) VISIBLE;

CREATE INDEX `fk_pagamento_tipoDesconto1_idx` ON `eventos`.`pagamento` (`pagamento_tipoDesconto_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`permissoesUsuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`permissoesUsuarios` ;

CREATE TABLE IF NOT EXISTS `eventos`.`permissoesUsuarios` (
  `permissoesUsuarios_permissoes_id` INT NOT NULL,
  `permissoesUsuarios_usuario_id` INT NOT NULL,
  PRIMARY KEY (`permissoesUsuarios_permissoes_id`, `permissoesUsuarios_usuario_id`),
  CONSTRAINT `fk_permissoes_has_usuario_permissoes1`
    FOREIGN KEY (`permissoesUsuarios_permissoes_id`)
    REFERENCES `eventos`.`permissoes` (`permissoes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permissoes_has_usuario_usuario1`
    FOREIGN KEY (`permissoesUsuarios_usuario_id`)
    REFERENCES `eventos`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_permissoes_has_usuario_usuario1_idx` ON `eventos`.`permissoesUsuarios` (`permissoesUsuarios_usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_permissoes_has_usuario_permissoes1_idx` ON `eventos`.`permissoesUsuarios` (`permissoesUsuarios_permissoes_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`inscritosProgramacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`inscritosProgramacao` ;

CREATE TABLE IF NOT EXISTS `eventos`.`inscritosProgramacao` (
  `inscritosProgramacao_id` INT NOT NULL AUTO_INCREMENT,
  `inscritosProgramacao_inscritos_id` INT NOT NULL,
  `inscritosProgramacao_programacao_id` INT NOT NULL,
  `inscritosProgramacao_dataHoraFrequencia` DATETIME NULL,
  `inscritosProgramacao_FrequenciaConfirmada` TINYINT NULL,
  PRIMARY KEY (`inscritosProgramacao_id`),
  CONSTRAINT `fk_inscritos_has_programacao_inscritos1`
    FOREIGN KEY (`inscritosProgramacao_inscritos_id`)
    REFERENCES `eventos`.`inscricao` (`inscricao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscritos_has_programacao_programacao1`
    FOREIGN KEY (`inscritosProgramacao_programacao_id`)
    REFERENCES `eventos`.`programacao` (`programacao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_inscritos_has_programacao_programacao1_idx` ON `eventos`.`inscritosProgramacao` (`inscritosProgramacao_programacao_id` ASC) VISIBLE;

CREATE INDEX `fk_inscritos_has_programacao_inscritos1_idx` ON `eventos`.`inscritosProgramacao` (`inscritosProgramacao_inscritos_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`imagemEvento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`imagemEvento` ;

CREATE TABLE IF NOT EXISTS `eventos`.`imagemEvento` (
  `imagemEvento_ID` INT NOT NULL AUTO_INCREMENT,
  `imagemEvento_caminho` VARCHAR(255) NOT NULL,
  `imagemEvento_descricao` VARCHAR(255) NULL,
  `imagemEvento_eventos_id` INT NOT NULL,
  PRIMARY KEY (`imagemEvento_ID`),
  CONSTRAINT `fk_imagemEvento_eventos1`
    FOREIGN KEY (`imagemEvento_eventos_id`)
    REFERENCES `eventos`.`eventos` (`eventos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_imagemEvento_eventos1_idx` ON `eventos`.`imagemEvento` (`imagemEvento_eventos_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`papelProgramacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`papelProgramacao` ;

CREATE TABLE IF NOT EXISTS `eventos`.`papelProgramacao` (
  `papelProgramacao_id` INT NOT NULL AUTO_INCREMENT,
  `papelProgramacao_inscricao_id` INT NOT NULL,
  `papelProgramacao_papel_id` INT NOT NULL,
  `papelProgramacao_programacao_id` INT NOT NULL,
  PRIMARY KEY (`papelProgramacao_id`),
  CONSTRAINT `fk_inscricao_has_papel_inscricao1`
    FOREIGN KEY (`papelProgramacao_inscricao_id`)
    REFERENCES `eventos`.`inscricao` (`inscricao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscricao_has_papel_papel1`
    FOREIGN KEY (`papelProgramacao_papel_id`)
    REFERENCES `eventos`.`papel` (`papel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_papelProgramacao_programacao1`
    FOREIGN KEY (`papelProgramacao_programacao_id`)
    REFERENCES `eventos`.`programacao` (`programacao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_inscricao_has_papel_papel1_idx` ON `eventos`.`papelProgramacao` (`papelProgramacao_papel_id` ASC) VISIBLE;

CREATE INDEX `fk_inscricao_has_papel_inscricao1_idx` ON `eventos`.`papelProgramacao` (`papelProgramacao_inscricao_id` ASC) VISIBLE;

CREATE INDEX `fk_papelProgramacao_programacao1_idx` ON `eventos`.`papelProgramacao` (`papelProgramacao_programacao_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `index5` ON `eventos`.`papelProgramacao` (`papelProgramacao_papel_id` ASC, `papelProgramacao_inscricao_id` ASC, `papelProgramacao_programacao_id` ASC) INVISIBLE;


-- -----------------------------------------------------
-- Table `eventos`.`imagemProgramacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos`.`imagemProgramacao` ;

CREATE TABLE IF NOT EXISTS `eventos`.`imagemProgramacao` (
  `imagemProgramacao_ID` INT NOT NULL AUTO_INCREMENT,
  `imagemProgramacao_caminho` VARCHAR(255) NOT NULL,
  `imagemProgramacao_descricao` VARCHAR(255) NULL,
  `imagemProgramacao_programacao_id` INT NOT NULL,
  PRIMARY KEY (`imagemProgramacao_ID`),
  CONSTRAINT `fk_imagemProgramacao_programacao1`
    FOREIGN KEY (`imagemProgramacao_programacao_id`)
    REFERENCES `eventos`.`programacao` (`programacao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_imagemProgramacao_programacao1_idx` ON `eventos`.`imagemProgramacao` (`imagemProgramacao_programacao_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
